Fix compilation failure
The time crate has advanced their version and changed inside since this was originally written, leading to compilation failure with error messages like:
"error[E0412]: cannot find type `Timespec` in crate `time`" and
"error[E0425]: cannot find function `get_time` in crate `time`".

This change pins the same minor version as the parent repo, thereby fixing the above mentioned issue.